### ISSUE TITLE
Distinguish between an ATM withdrawal or POS purchase

### ISSUE THREAD

**Issue by DonChangfoot** [appliedpayments/ISO-Open-API-Adaptor#30]
From a Mojaloop API perspective it's supposed to be
TransactionScenario to WITHDRAWAL
TransactionInitiator to PAYEE
TransactionInitiatorType to AGENT

and for ATM it's
TransactionScenario to WITHDRAWAL
TransactionInitiator to PAYEE
TransactionInitiatorType to DEVICE

We therefore need to determine the type of transaction from the ISO message so the mojaloop transaction type can be set correctly

**Comment by DonChangfoot** [comment]
Use field 3 of the 0100 message to determine which type of transaction it is. This needs to be configured per connection as different iso implementations may use a custom code set

**Comment by revan-wy** [comment]
Addressed by PR #31
