### ISSUE TITLE
Logging in services

### ISSUE THREAD

**Issue by DonChangfoot** [appliedpayments/ISO-Open-API-Adaptor#8]
Modify services (transaction requests, quotes, authorization, transfers) to take a logger in the constructor then use it to add logging in each of it's functions.

e.g. Quotes service - create function
add logging to say 'creating quote. quote request: ' + JSON.stringify(quoteRequest) + ' fees: ' + JSON.stringify(fees)

**Comment by revan-wy** [comment]
Addressed by PR #35
